// counter-react/src/application/components/counter/GlobalCounter.tsx
import 'promise.prototype.finally'
import {Count} from '../../../domain/entities/Count';
import {CountPersistRepository, isFail} from '../../../domain/repository/CountPersistRepository';
import {TYPES} from "../../context/di-types";
import {CountVolatileRepository} from "../../../domain/repository/CountVolatileRepository";
import * as React from "react";
import {lazyInject} from "../../context/context";

export interface State {
  count: number
  loadingCount: number
}

export class GlobalCounter extends React.Component<{}, State> {

  @lazyInject(TYPES.CountPersistRepository) private countPRepo?: CountPersistRepository;
  @lazyInject(TYPES.CountVolatileRepository) private countSRepo?: CountVolatileRepository;

  constructor(props: {}) {
    super(props)
    this.state = {
      loadingCount: 0,
      count: 0,
    }
  }

  increment(amount: number):void {
    this.countSRepo!.increment(amount)
  }

  decrement(amount: number):void {
    this.countSRepo!.decrement(amount)
  }

  reload(): void {
    this.setState({loadingCount: this.state.loadingCount + 1})
    this.countPRepo!.fetchCount()
      .then(count => this.countSRepo!.update(count))
      .catch(e => console.error(e))
      .finally(() => {
        this.setState({loadingCount: this.state.loadingCount - 1})
      })
  }

  save(): void {
    this.setState({loadingCount: this.state.loadingCount + 1})
    this.countPRepo!.saveCount(new Count(this.state.count))
      .then((result) => {
        if(isFail(result)) {
          window.alert(result.err.message)
        } else {
          window.alert('セーブしました')
        }
      })
      .catch(e => {
        console.error(e)
        window.alert('サーバーに繋がりませんでした')
      })
      .finally(() => {
        this.setState({loadingCount: this.state.loadingCount - 1})
      })
  }

  componentDidMount(){
    this.countSRepo!.getStateObservable()
      .subscribe((count: Count) => {
        this.setState({...this.state, count: count.getValue()})
      })
    this.reload()
  }

  render() {
    return (
      <div>
        <h2>Global Counter</h2>
        <p>{`global count: ${this.state.count}`}</p>
        <button onClick={() => this.increment(3)}>Global Increment 3</button>
        <button onClick={() => this.decrement(2)}>Global Decrement 2</button>
        <button onClick={() => this.save()}>Global save</button>
        <button onClick={() => this.reload()}>Global reload</button>
        {(this.state.loadingCount === 0) ? null : <p>loading</p>}
      </div>
    )
  }
}

// counter-angular/src/application/components/counter/globalCounter/global-counter.ts
import { Component, Inject, OnInit } from '@angular/core'
import { CountVolatileRepository } from '../../../../domain/repository/CountVolatileRepository'
import { COUNT_P_REPO, COUNT_V_REPO } from '../../../context/inject'
import {
  CountPersistRepository,
  isFail
} from '../../../../domain/repository/CountPersistRepository'
import { Count } from '../../../../domain/entities/Count'

@Component({
  selector: 'global-counter',
  templateUrl: './global-counter.html',
  styleUrls: ['./global-counter.scss']
})
export class GlobalCounter implements OnInit {
  count: number
  loadingCount: number

  public constructor(
    @Inject(COUNT_P_REPO) private countPRepo: CountPersistRepository,
    @Inject(COUNT_V_REPO) private countVRepo: CountVolatileRepository
  ) {
    this.count = 0
    this.loadingCount = 0
  }

  ngOnInit(): void {
    this.countVRepo.getStateObservable().subscribe((c: Count) => (this.count = c.getValue()))
    this.reload()
  }

  increment(num: number): void {
    this.countVRepo.increment(num)
  }

  decrement(num: number): void {
    this.countVRepo.decrement(num)
  }

  reload(): void {
    this.loadingCount = this.loadingCount + 1
    this.countPRepo
      .fetchCount()
      .then((count) => this.countVRepo.update(count))
      .catch((e) => console.error(e))
      .finally(() => (this.loadingCount = this.loadingCount - 1))
  }

  save(): void {
    this.loadingCount = this.loadingCount + 1
    this.countPRepo
      .saveCount(new Count(this.count))
      .then((result) => {
        if (isFail(result)) {
          window.alert(result.err.message)
        } else {
          window.alert('セーブしました')
        }
      })
      .catch((e) => {
        console.error(e)
        window.alert('サーバーに繋がりませんでした')
      })
      .finally(() => (this.loadingCount = this.loadingCount - 1))
  }
}
