// counter-angular/src/application/components/counter/localCounter/local-counter.ts
import { Component } from '@angular/core'

@Component({
  selector: 'local-counter',
  templateUrl: './local-counter.html',
  styleUrls: ['./local-counter.scss']
})
export class LocalCounter {
  internalCount: number

  public constructor() {
    this.internalCount = 0
  }

  increment(num: number): void {
    this.internalCount = this.internalCount + num
  }

  decrement(num: number): void {
    this.internalCount = this.internalCount - num
  }
}

// counter-react/src/application/components/counter/LocalCounter.tsx
import * as React from "react";

export interface State {
  internalCount: number
}

export class LocalCounter extends React.Component<{}, State> {

  constructor(props: {}) {
    super(props)
    this.state = {
      internalCount: 0,
    }
  }

  internalIncrement(num: number): void {
    this.setState({internalCount: this.state.internalCount + num})
  }

  internalDecrement(num: number):void {
    this.setState({internalCount: this.state.internalCount - num})
  }

  render() {
    return (
      <div>
        <h2>Local Counter</h2>
        <p>{`internal count: ${this.state.internalCount}`}</p>
        <button onClick={() => this.internalIncrement(3)}>Internal Increment 3</button>
        <button onClick={() => this.internalDecrement(2)}>Internal Decrement 2</button>
      </div>
    )
  }
}
